apiVersion: v1
kind: ConfigMap
metadata:
  name: pocket-ranger-config
  namespace: pocket-ranger
  labels:
    app: pocket-ranger
    component: config
data:
  NODE_ENV: "production"
  EXPO_PUBLIC_API_URL: "https://api.pocketranger.app"
  PORT: "8081"
  LOG_LEVEL: "info"
  # Add other non-sensitive configuration here
  CORS_ORIGIN: "*"
  API_TIMEOUT: "30000"
  MAX_REQUEST_SIZE: "10mb"