apiVersion: v1
kind: ServiceAccount
metadata:
  name: pocket-ranger-sa
  namespace: pocket-ranger
  labels:
    app: pocket-ranger
    component: rbac
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pocket-ranger-role
  namespace: pocket-ranger
  labels:
    app: pocket-ranger
    component: rbac
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pocket-ranger-rolebinding
  namespace: pocket-ranger
  labels:
    app: pocket-ranger
    component: rbac
subjects:
- kind: ServiceAccount
  name: pocket-ranger-sa
  namespace: pocket-ranger
roleRef:
  kind: Role
  name: pocket-ranger-role
  apiGroup: rbac.authorization.k8s.io